### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ewanpayne** [malothnaresh/mat-select-autocomplete#1]
When i choose only ONE component is impossible to view one element. 
It works only two or more... 

1. Reset 
2. Try to choose only ONE 
3. click out of dropdown. It's impossible.

**Comment by malothnaresh** [comment]
Could you please provide steps to reproduce ?

**Comment by ewanpayne** [comment]
I found that the reset button causes a screen block IF you only select 1 item on the list. This makes multiple selection obbligatory.

1. click on reset 
2. all items become deselected
3. select only 1 element 
4. everything becomes unclickable untile you select the 2nd element.

**Comment by malothnaresh** [comment]
Release number 1.2.4 has fix for it. Please take update.
