### ISSUE TITLE
Warning using the disabled and using ngModel on the same form field as formControl

### ISSUE THREAD

**Issue by LauraNavarroGalvan** [malothnaresh/mat-select-autocomplete#4]
I'm trying to use the implementation for Angular 7, but I get these warnings and I'm not using disable or ngmodel
![image](https://user-images.githubusercontent.com/39338495/61497536-66aeff80-a985-11e9-9b44-a943f11ebd4d.png)

**Comment by malothnaresh** [comment]
Not able to reproduce. Could you please check with your implementation or provide steps to reproduce ?

**Comment by LauraNavarroGalvan** [comment]
you can see the same warnings in the demo console
https://stackblitz.com/edit/mat-select-autocomplete

**Comment by malothnaresh** [comment]
Release 1.2.4 has fixed first warning. Would come up with solution for second warning later.

**Comment by malothnaresh** [comment]
Partial fix committed. The library does not support another part of it.

**Comment by bachrc** [comment]
This issue is still here :/
