### ISSUE TITLE
Enter the invalid the chars, the Select All(Check box) box - automatically selected

### ISSUE THREAD

**Issue by maariselvamsubramanian** [malothnaresh/mat-select-autocomplete#5]
Enter the invalid the chars(Chars did not match the options), the Select All(Check box) box - automatically selected

![image](https://user-images.githubusercontent.com/14921114/61548691-e6af9500-aa6b-11e9-9499-bb8aeb1277ea.png)

**Comment by malothnaresh** [comment]
Fixed the issue with commit ID: 9210733068e4906afe9e69a3f2b2fe844b4801fc. Please take update and verify.
