### ISSUE TITLE
Fix Usage in npm

### ISSUE THREAD

**Issue by sambhalgithub** [malothnaresh/mat-select-autocomplete#6]
Install mat-select-autocomplete using npm

    npm i mat-select-autocomplete

In AppModule,

    import { SelectAutocompleteModule } from  'mat-select-autocomplete';

Add it to your AppModule import list 

    imports: [
	    ...
	    SelectAutocompleteModule,
	    ...
    ],

Add material theme to your styles.scss as 

    @import "~@angular/material/prebuilt-themes/indigo-pink.css"; 

Add Material icons font to index.html as 

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

Now use with configurations specified in document.

**Comment by sambhalgithub** [comment]
I was not able to use this module because of the bad usage mentioned on npm page. Plz update it.

**Comment by malothnaresh** [comment]
Could you please describe the bug you were facing... ? Because, those must be correct steps.

**Comment by sambhalgithub** [comment]
The steps at npm page are not correct, I am suggesting you to add this formatted description at npm page.

**Comment by malothnaresh** [comment]
Sure.

**Comment by sambhalgithub** [comment]
Btw thanks for the plugin.
Does this plugin supports option groups? Just like **Single selection with option groups** in  [https://stackblitz.com/github/gqaiymzx](url)
